
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: secret
  host: db
  # password:
  # socket: /tmp/mysql.sock

development:
  <<: *default
  database: sup_app_development

test:
  <<: *default
  database: sup_app_test

production:
  <<: *default
  database: sup_app_production
  username: root
  password: <%= ENV[DATABASE_PASSWORD] %>
  socket: /var/lib/mysql/mysql.sock
